[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables configuration
[build.environment]
  # Only include non-secret environment variables here
  NODE_VERSION = "18"

